name: Deploy to Vercel

on:
  push:
    branches:
      - main

concurrency:
  group: vercel-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'docs:')"
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build web
        run: bun tko web build
        env:
          NODE_ENV: production
          ONE_SERVER_URL: ${{ secrets.ONE_SERVER_URL }}
          VITE_POSTHOG_API_KEY: ${{ secrets.VITE_POSTHOG_API_KEY }}
          VITE_POSTHOG_HOST: ${{ secrets.VITE_POSTHOG_HOST }}
          VITE_WEB_HOST: ${{ secrets.VITE_WEB_HOST }}

      - name: Deploy to Vercel
        run: npx vercel deploy dist/client --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
